version: '3.9'
services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend_dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
